var continents = 
{ Africa: 
   [ { abbr: 'AO', name: 'Angola' },
     { abbr: 'BI', name: 'Burundi' },
     { abbr: 'BJ', name: 'Benin' },
     { abbr: 'BW', name: 'Botswana' },
     { abbr: 'CF', name: 'Central African Republic' },
     { abbr: 'CG', name: 'Congo' },
     { abbr: 'CM', name: 'Cameroon' },
     { abbr: 'CV', name: 'Cape Verde' },
     { abbr: 'DJ', name: 'Djibouti' },
     { abbr: 'DZ', name: 'Algeria' },
     { abbr: 'EG', name: 'Egypt' },
     { abbr: 'ER', name: 'Eritrea' },
     { abbr: 'ET', name: 'Ethiopia' },
     { abbr: 'GA', name: 'Gabon' },
     { abbr: 'GH', name: 'Ghana' },
     { abbr: 'GM', name: 'Gambia' },
     { abbr: 'GN', name: 'Guinea' },
     { abbr: 'GQ', name: 'Equatorial Guinea' },
     { abbr: 'GW', name: 'Guinea-Bissau' },
     { abbr: 'KE', name: 'Kenya' },
     { abbr: 'KM', name: 'Comoros' },
     { abbr: 'LR', name: 'Liberia' },
     { abbr: 'LS', name: 'Lesotho' },
     { abbr: 'LY', name: 'Libya' },
     { abbr: 'MA', name: 'Morocco' },
     { abbr: 'MG', name: 'Madagascar' },
     { abbr: 'ML', name: 'Mali' },
     { abbr: 'MR', name: 'Mauritania' },
     { abbr: 'MU', name: 'Mauritius' },
     { abbr: 'MW', name: 'Malawi' },
     { abbr: 'MZ', name: 'Mozambique' },
     { abbr: 'NA', name: 'Namibia' },
     { abbr: 'NE', name: 'Niger' },
     { abbr: 'NG', name: 'Nigeria' },
     { abbr: 'RW', name: 'Rwanda' },
     { abbr: 'SC', name: 'Seychelles' },
     { abbr: 'SD', name: 'Sudan' },
     { abbr: 'SL', name: 'Sierra Leone' },
     { abbr: 'SN', name: 'Senegal' },
     { abbr: 'SO', name: 'Somalia' },
     { abbr: 'ST', name: 'Sao Tome and Principe' },
     { abbr: 'SZ', name: 'Swaziland' },
     { abbr: 'TD', name: 'Chad' },
     { abbr: 'TG', name: 'Togo' },
     { abbr: 'TN', name: 'Tunisia' },
     { abbr: 'TZ', name: 'Tanzania' },
     { abbr: 'UG', name: 'Uganda' },
     { abbr: 'ZA', name: 'South Africa' },
     { abbr: 'ZM', name: 'Zambia' },
     { abbr: 'ZW', name: 'Zimbabwe' } ],
  Asia: 
   [ { abbr: 'AE', name: 'United Arab Emirates' },
     { abbr: 'AF', name: 'Afghanistan' },
     { abbr: 'BD', name: 'Bangladesh' },
     { abbr: 'BH', name: 'Bahrain' },
     { abbr: 'BT', name: 'Bhutan' },
     { abbr: 'CN', name: 'China' },
     { abbr: 'ID', name: 'Indonesia' },
     { abbr: 'IL', name: 'Israel' },
     { abbr: 'IN', name: 'India' },
     { abbr: 'IQ', name: 'Iraq' },
     { abbr: 'IR', name: 'Iran' },
     { abbr: 'JO', name: 'Jordan' },
     { abbr: 'JP', name: 'Japan' },
     { abbr: 'KG', name: 'Kyrgyzstan' },
     { abbr: 'KH', name: 'Cambodia' },
     { abbr: 'KW', name: 'Kuwait' },
     { abbr: 'KZ', name: 'Kazakhstan' },
     { abbr: 'LA', name: 'Laos' },
     { abbr: 'LB', name: 'Lebanon' },
     { abbr: 'LK', name: 'Sri Lanka' },
     { abbr: 'MN', name: 'Mongolia' },
     { abbr: 'MV', name: 'Maldives' },
     { abbr: 'MY', name: 'Malaysia' },
     { abbr: 'NP', name: 'Nepal' },
     { abbr: 'OM', name: 'Oman' },
     { abbr: 'PH', name: 'Philippines' },
     { abbr: 'PK', name: 'Pakistan' },
     { abbr: 'QA', name: 'Qatar' },
     { abbr: 'RU', name: 'Russian Federation' },
     { abbr: 'SA', name: 'Saudi Arabia' },
     { abbr: 'SG', name: 'Singapore' },
     { abbr: 'SY', name: 'Syria' },
     { abbr: 'TH', name: 'Thailand' },
     { abbr: 'TJ', name: 'Tajikistan' },
     { abbr: 'TM', name: 'Turkmenistan' },
     { abbr: 'TP', name: 'East Timor' },
     { abbr: 'TR', name: 'Turkey' },
     { abbr: 'UZ', name: 'Uzbekistan' },
     { abbr: 'YE', name: 'Yemen' } ],
  Europe: 
   [ { abbr: 'AD', name: 'Andorra' },
     { abbr: 'AL', name: 'Albania' },
     { abbr: 'AM', name: 'Armenia' },
     { abbr: 'AT', name: 'Austria' },
     { abbr: 'AZ', name: 'Azerbaijan' },
     { abbr: 'BA', name: 'Bosnia and Herzegovina' },
     { abbr: 'BE', name: 'Belgium' },
     { abbr: 'BG', name: 'Bulgaria' },
     { abbr: 'BY', name: 'Belarus' },
     { abbr: 'CH', name: 'Switzerland' },
     { abbr: 'CY', name: 'Cyprus' },
     { abbr: 'CZ', name: 'Czech Republic' },
     { abbr: 'DE', name: 'Germany' },
     { abbr: 'DK', name: 'Denmark' },
     { abbr: 'EE', name: 'Estonia' },
     { abbr: 'ES', name: 'Spain' },
     { abbr: 'FI', name: 'Finland' },
     { abbr: 'FR', name: 'France' },
     { abbr: 'GE', name: 'Georgia' },
     { abbr: 'GR', name: 'Greece' },
     { abbr: 'HU', name: 'Hungary' },
     { abbr: 'IE', name: 'Ireland' },
     { abbr: 'IS', name: 'Iceland' },
     { abbr: 'IT', name: 'Italy' },
     { abbr: 'LI', name: 'Liechtenstein' },
     { abbr: 'LT', name: 'Lithuania' },
     { abbr: 'LU', name: 'Luxembourg' },
     { abbr: 'LV', name: 'Latvia' },
     { abbr: 'MC', name: 'Monaco' },
     { abbr: 'MD', name: 'Moldova' },
     { abbr: 'MK', name: 'Macedonia' },
     { abbr: 'MT', name: 'Malta' },
     { abbr: 'NL', name: 'Netherlands' },
     { abbr: 'NO', name: 'Norway' },
     { abbr: 'PL', name: 'Poland' },
     { abbr: 'PT', name: 'Portugal' },
     { abbr: 'RO', name: 'Romania' },
     { abbr: 'SE', name: 'Sweden' },
     { abbr: 'SI', name: 'Slovenia' },
     { abbr: 'SK', name: 'Slovakia' },
     { abbr: 'SM', name: 'San Marino' },
     { abbr: 'UA', name: 'Ukraine' },
     { abbr: 'UK', name: 'United Kingdom' } ],
  'North America': 
   [ { abbr: 'AG', name: 'Antigua and Barbuda' },
     { abbr: 'BB', name: 'Barbados' },
     { abbr: 'BS', name: 'Bahamas' },
     { abbr: 'BZ', name: 'Belize' },
     { abbr: 'CA', name: 'Canada' },
     { abbr: 'CR', name: 'Costa Rica' },
     { abbr: 'CU', name: 'Cuba' },
     { abbr: 'DM', name: 'Dominica' },
     { abbr: 'DO', name: 'Dominican Republic' },
     { abbr: 'GD', name: 'Grenada' },
     { abbr: 'GT', name: 'Guatemala' },
     { abbr: 'HN', name: 'Honduras' },
     { abbr: 'HT', name: 'Haiti' },
     { abbr: 'JM', name: 'Jamaica' },
     { abbr: 'KN', name: 'Saint Kitts and Nevis' },
     { abbr: 'LC', name: 'Saint Lucia' },
     { abbr: 'MX', name: 'Mexico' },
     { abbr: 'NI', name: 'Nicaragua' },
     { abbr: 'PA', name: 'Panama' },
     { abbr: 'SV', name: 'El Salvador' },
     { abbr: 'TT', name: 'Trinidad and Tobago' },
     { abbr: 'US', name: 'United States' },
     { abbr: 'VC', name: 'Saint Vincent and the Grenadines' } ],
  Oceania: 
   [ { abbr: 'AU', name: 'Australia' },
     { abbr: 'FJ', name: 'Fiji' },
     { abbr: 'KI', name: 'Kiribati' },
     { abbr: 'MH', name: 'Marshall Islands' },
     { abbr: 'NR', name: 'Nauru' },
     { abbr: 'PG', name: 'Papua New Guinea' },
     { abbr: 'PW', name: 'Palau' },
     { abbr: 'SB', name: 'Solomon Islands' },
     { abbr: 'TO', name: 'Tonga' },
     { abbr: 'TV', name: 'Tuvalu' },
     { abbr: 'VU', name: 'Vanuatu' },
     { abbr: 'WS', name: 'Samoa' } ],
  'South America': 
   [ { abbr: 'AR', name: 'Argentina' },
     { abbr: 'BO', name: 'Bolivia' },
     { abbr: 'BR', name: 'Brazil' },
     { abbr: 'CL', name: 'Chile' },
     { abbr: 'CO', name: 'Colombia' },
     { abbr: 'EC', name: 'Ecuador' },
     { abbr: 'GY', name: 'Guyana' },
     { abbr: 'PE', name: 'Peru' },
     { abbr: 'PY', name: 'Paraguay' },
     { abbr: 'SR', name: 'Suriname' },
     { abbr: 'UY', name: 'Uruguay' },
     { abbr: 'VE', name: 'Venezuela' } ] };

module.exports = continents;